// <auto-generated />
using System;
using ImportCostPro.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImportCostPro.Data.Migrations
{
    [DbContext(typeof(ImportCostDbContext))]
    [Migration("20260603172000_AddTablesOrdenGastoProductoEImportacion")]
    partial class AddTablesOrdenGastoProductoEImportacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImportCostPro.Data.Entities.CalculoLandedCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CifTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoTotalImportacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FleteTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FobTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GastosLocalesTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrdenImportacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeItbisUsado")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeTasaServicioUsado")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SeguroTotalLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalArancel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIsc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalItbis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTasaServicio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenImportacionId");

                    b.ToTable("CalculosLandedCost");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.CalculoLandedCostDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculoLandedCostId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoTotalImportado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoUnitarioImportado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FleteAsignado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FobLocalTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FobOriginalUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GastosLocalesAsignados")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MargenDeseadoAplicado")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MontoArancel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoIsc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoItbis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTasaServicio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVentaSugerido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SeguroAsignado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorCif")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CalculoLandedCostId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesLandedCost");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.CategoriaArancelaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("AplicaImpuestoSelectivo")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaItbis")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoArancelario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PorcentajeArancel")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeImpuestoSelectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("CategoriasArancelarias", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.ConfiguracionImpuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("PorcentajeITBIS")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeTasaServicioAduanal")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesImpuestos", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Importador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("Rnc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.HasIndex("Rnc")
                        .IsUnique();

                    b.ToTable("Importadores", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<bool>("EsMonedaLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoISO")
                        .IsUnique();

                    b.ToTable("Monedas", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.OrdenGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaGasto")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoDistribucion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MontoEnMonedaLocal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("OrdenImportacionId")
                        .HasColumnType("int");

                    b.Property<string>("TipoGasto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.HasIndex("OrdenImportacionId");

                    b.ToTable("OrdenGastos", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.OrdenImportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Arancel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CIF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoFOB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Abierta");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ITBIS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ImportadorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ImpuestoSelectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModalidadTransporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaisOrigenId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioSugerido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TasaAduanal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImportadorId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("NumeroOrden")
                        .IsUnique();

                    b.HasIndex("PaisOrigenId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("OrdenesImportacion", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.OrdenProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("FOBTotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MargenGananciaDeseado")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("OrdenImportacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoTotal")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("PrecioUnitarioFOB")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VolumenTotal")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenImportacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenProductos", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoISO")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Paises", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Alto")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("Ancho")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("CategoriaArancelariaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoReferencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("Largo")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.Property<int>("PaisOrigenId")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoUnitario")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaArancelariaId");

                    b.HasIndex("PaisId");

                    b.HasIndex("PaisOrigenId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MonedaPrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PaisOrigenId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MonedaPrincipalId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("PaisOrigenId");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.TasaCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonedaDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("MonedaOrigenId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("MonedaDestinoId");

                    b.HasIndex("MonedaOrigenId");

                    b.ToTable("TasasCambio", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.CalculoLandedCost", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.OrdenImportacion", "OrdenImportacion")
                        .WithMany()
                        .HasForeignKey("OrdenImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.CalculoLandedCostDetalle", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.CalculoLandedCost", "CalculoLandedCost")
                        .WithMany("Detalles")
                        .HasForeignKey("CalculoLandedCostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Data.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalculoLandedCost");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Importador", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.OrdenGasto", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Data.Entities.OrdenImportacion", "OrdenImportacion")
                        .WithMany("Gastos")
                        .HasForeignKey("OrdenImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");

                    b.Navigation("OrdenImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.OrdenImportacion", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.Importador", "Importador")
                        .WithMany()
                        .HasForeignKey("ImportadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Data.Entities.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Data.Entities.Pais", "PaisOrigen")
                        .WithMany()
                        .HasForeignKey("PaisOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Data.Entities.Proveedor", "Proveedor")
                        .WithMany("OrdenesImportacion")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Importador");

                    b.Navigation("Moneda");

                    b.Navigation("PaisOrigen");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.OrdenProducto", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.OrdenImportacion", "OrdenImportacion")
                        .WithMany("Productos")
                        .HasForeignKey("OrdenImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Data.Entities.Producto", "Producto")
                        .WithMany("OrdenProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenImportacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Producto", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.CategoriaArancelaria", "CategoriaArancelaria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaArancelariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Data.Entities.Pais", null)
                        .WithMany("Productos")
                        .HasForeignKey("PaisId");

                    b.HasOne("ImportCostPro.Data.Entities.Pais", "PaisOrigen")
                        .WithMany()
                        .HasForeignKey("PaisOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaArancelaria");

                    b.Navigation("PaisOrigen");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Proveedor", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.Moneda", "MonedaPrincipal")
                        .WithMany()
                        .HasForeignKey("MonedaPrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Data.Entities.Pais", "PaisOrigen")
                        .WithMany("Proveedores")
                        .HasForeignKey("PaisOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonedaPrincipal");

                    b.Navigation("PaisOrigen");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.TasaCambio", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.Moneda", "MonedaDestino")
                        .WithMany("TasasCambioDestino")
                        .HasForeignKey("MonedaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Data.Entities.Moneda", "MonedaOrigen")
                        .WithMany("TasasCambioOrigen")
                        .HasForeignKey("MonedaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonedaDestino");

                    b.Navigation("MonedaOrigen");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.CalculoLandedCost", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.CategoriaArancelaria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Moneda", b =>
                {
                    b.Navigation("TasasCambioDestino");

                    b.Navigation("TasasCambioOrigen");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.OrdenImportacion", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Pais", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Producto", b =>
                {
                    b.Navigation("OrdenProductos");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Proveedor", b =>
                {
                    b.Navigation("OrdenesImportacion");
                });
#pragma warning restore 612, 618
        }
    }
}
