// <auto-generated />
using System;
using ImportCostPro.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImportCostPro.Data.Migrations
{
    [DbContext(typeof(ImportCostDbContext))]
    [Migration("20260524021550_AgregarModuloFinanzas")]
    partial class AgregarModuloFinanzas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImportCostPro.Data.Entities.CategoriaArancelaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("AplicaImpuestoSelectivo")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaItbis")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoArancelario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PorcentajeArancel")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeImpuestoSelectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("CategoriasArancelarias", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.ConfiguracionImpuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("PorcentajeITBIS")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeTasaServicioAduanal")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesImpuestos", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<bool>("EsMonedaLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoISO")
                        .IsUnique();

                    b.ToTable("Monedas", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Alto")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("CategoriaArancelariaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoReferencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Largo")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PaisOrigenId")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoUnitario")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaArancelariaId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.TasaCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonedaDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("MonedaOrigenId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("MonedaDestinoId");

                    b.HasIndex("MonedaOrigenId");

                    b.ToTable("TasasCambio", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Producto", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.CategoriaArancelaria", "CategoriaArancelaria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaArancelariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaArancelaria");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.TasaCambio", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.Moneda", "MonedaDestino")
                        .WithMany("TasasCambioDestino")
                        .HasForeignKey("MonedaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Data.Entities.Moneda", "MonedaOrigen")
                        .WithMany("TasasCambioOrigen")
                        .HasForeignKey("MonedaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonedaDestino");

                    b.Navigation("MonedaOrigen");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.CategoriaArancelaria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Moneda", b =>
                {
                    b.Navigation("TasasCambioDestino");

                    b.Navigation("TasasCambioOrigen");
                });
#pragma warning restore 612, 618
        }
    }
}
