// <auto-generated />
using ImportCostPro.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImportCostPro.Data.Migrations
{
    [DbContext(typeof(ImportCostDbContext))]
    partial class ImportCostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImportCostPro.Data.Entities.CategoriaArancelaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("AplicaImpuestoSelectivo")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaItbis")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoArancelario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PorcentajeArancel")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeImpuestoSelectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("CategoriasArancelarias", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Alto")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("CategoriaArancelariaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoReferencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Largo")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PaisOrigenId")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoUnitario")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaArancelariaId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.Producto", b =>
                {
                    b.HasOne("ImportCostPro.Data.Entities.CategoriaArancelaria", "CategoriaArancelaria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaArancelariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaArancelaria");
                });

            modelBuilder.Entity("ImportCostPro.Data.Entities.CategoriaArancelaria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
